apiVersion: v1
kind: Service
metadata:
  name: iqg-svc
  namespace: iqg
  labels:
    name: iqg-svc
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 3000
  selector:
    app: iqg-app
